/*
 * File: lqr_k.c
 *
 * MATLAB Coder version            : 23.2
 * C/C++ source code generated on  : 12-Sep-2024 11:49:17
 */

/* Include Files */
#include "lqr_k.h"
#include "rt_nonfinite.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Declarations */
static float rt_powf_snf(float u0, float u1);

/* Function Definitions */
/*
 * Arguments    : float u0
 *                float u1
 * Return Type  : float
 */
static float rt_powf_snf(float u0, float u1)
{
  float y;
  if (rtIsNaNF(u0) || rtIsNaNF(u1)) {
    y = rtNaNF;
  } else {
    float f;
    float f1;
    f = fabsf(u0);
    f1 = fabsf(u1);
    if (rtIsInfF(u1)) {
      if (f == 1.0F) {
        y = 1.0F;
      } else if (f > 1.0F) {
        if (u1 > 0.0F) {
          y = rtInfF;
        } else {
          y = 0.0F;
        }
      } else if (u1 > 0.0F) {
        y = 0.0F;
      } else {
        y = rtInfF;
      }
    } else if (f1 == 0.0F) {
      y = 1.0F;
    } else if (f1 == 1.0F) {
      if (u1 > 0.0F) {
        y = u0;
      } else {
        y = 1.0F / u0;
      }
    } else if (u1 == 2.0F) {
      y = u0 * u0;
    } else if ((u1 == 0.5F) && (u0 >= 0.0F)) {
      y = sqrtf(u0);
    } else if ((u0 < 0.0F) && (u1 > floorf(u1))) {
      y = rtNaNF;
    } else {
      y = powf(u0, u1);
    }
  }
  return y;
}

/*
 * LQR_K
 *     K = LQR_K(L0)
 *
 * Arguments    : float L0
 *                float K[12]
 * Return Type  : void
 */
void lqr_k(float L0, float K[12])
{
  float t2;
  float t3;
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     2024-09-12 11:44:51 */
  t2 = L0 * L0;
  t3 = rt_powf_snf(L0, 3.0F);
  K[0] = ((L0 * -209.031708F + t2 * 337.996185F) - t3 * 351.829376F) +
         0.160725176F;
  K[1] =
      ((L0 * 78.0235062F - t2 * 349.234589F) + t3 * 519.064148F) + 2.35644984F;
  K[2] =
      ((L0 * -16.201952F - t2 * 33.9593086F) + t3 * 39.0960197F) + 0.104744315F;
  K[3] =
      ((L0 * 10.7003326F - t2 * 33.3030167F) + t3 * 42.497242F) + 0.15521954F;
  K[4] =
      ((L0 * -148.012711F + t2 * 548.653076F) - t3 * 760.835327F) - 1.53218317F;
  K[5] =
      ((L0 * -28.9464931F - t2 * 30.860033F) + t3 * 153.667969F) + 12.7470455F;
  K[6] =
      ((L0 * -99.6581421F + t2 * 320.067932F) - t3 * 428.42749F) - 1.87355125F;
  K[7] =
      ((L0 * -11.7475967F - t2 * 41.1940765F) + t3 * 123.07608F) + 7.98848057F;
  K[8] =
      ((L0 * -208.870346F + t2 * 407.084259F) - t3 * 290.347168F) + 51.4304886F;
  K[9] =
      ((L0 * 197.340012F - t2 * 667.772034F) + t3 * 852.934814F) + 43.2635078F;
  K[10] =
      ((L0 * -23.2012138F + t2 * 34.3328857F) - t3 * 12.1052666F) + 7.39884567F;
  K[11] = ((L0 * 26.225378F - t2 * 80.324646F) + t3 * 94.236763F) + 3.54146957F;
}

/*
 * File trailer for lqr_k.c
 *
 * [EOF]
 */
