/*
 * File: lqr_k.c
 *
 * MATLAB Coder version            : 23.2
 * C/C++ source code generated on  : 10-Oct-2024 14:36:29
 */

/* Include Files */
#include "lqr_k.h"
#include "rt_nonfinite.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Declarations */
static float rt_powf_snf(float u0, float u1);

/* Function Definitions */
/*
 * Arguments    : float u0
 *                float u1
 * Return Type  : float
 */
static float rt_powf_snf(float u0, float u1)
{
  float y;
  if (rtIsNaNF(u0) || rtIsNaNF(u1)) {
    y = rtNaNF;
  } else {
    float f;
    float f1;
    f = fabsf(u0);
    f1 = fabsf(u1);
    if (rtIsInfF(u1)) {
      if (f == 1.0F) {
        y = 1.0F;
      } else if (f > 1.0F) {
        if (u1 > 0.0F) {
          y = rtInfF;
        } else {
          y = 0.0F;
        }
      } else if (u1 > 0.0F) {
        y = 0.0F;
      } else {
        y = rtInfF;
      }
    } else if (f1 == 0.0F) {
      y = 1.0F;
    } else if (f1 == 1.0F) {
      if (u1 > 0.0F) {
        y = u0;
      } else {
        y = 1.0F / u0;
      }
    } else if (u1 == 2.0F) {
      y = u0 * u0;
    } else if ((u1 == 0.5F) && (u0 >= 0.0F)) {
      y = sqrtf(u0);
    } else if ((u0 < 0.0F) && (u1 > floorf(u1))) {
      y = rtNaNF;
    } else {
      y = powf(u0, u1);
    }
  }
  return y;
}

/*
 * LQR_K
 *     K = LQR_K(L0)
 *
 * Arguments    : float L0
 *                float K[12]
 * Return Type  : void
 */
void lqr_k(float L0, float K[12])
{
  float t2;
  float t3;
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     2024-10-10 14:07:08 */
  t2 = L0 * L0;
  t3 = rt_powf_snf(L0, 3.0F);
  K[0] = ((L0 * -70.8812561F + t2 * 190.103424F) - t3 * 218.127762F) -
         0.718286157F;
  K[1] =
      ((L0 * 11.3166294F - t2 * 56.7431717F) + t3 * 83.281868F) + 0.652603209F;
  K[2] =
      ((L0 * -8.71799F + t2 * 19.3644142F) - t3 * 25.3193283F) - 0.137506858F;
  K[3] =
      ((L0 * -0.157311395F - t2 * 3.09572864F) + t3 * 6.34178209F) + 0.3028557F;
  K[4] = ((L0 * -5.96829557F + t2 * 20.8166199F) - t3 * 26.3523903F) -
         0.280560076F;
  K[5] = ((L0 * 0.288214505F - t2 * 4.76720142F) + t3 * 8.80896568F) +
         0.196985453F;
  K[6] =
      ((L0 * -8.9553318F + t2 * 30.7990189F) - t3 * 39.4572601F) - 0.626922786F;
  K[7] = ((L0 * 0.229402408F - t2 * 6.97924423F) + t3 * 13.4427252F) +
         0.334644884F;
  K[8] = ((L0 * -8.28045F + t2 * 19.5102043F) - t3 * 18.645195F) + 1.82882273F;
  K[9] =
      ((L0 * 3.64877677F - t2 * 10.9863186F) + t3 * 12.3019733F) + 1.34404695F;
  K[10] = ((L0 * -4.29149961F + t2 * 11.1992455F) - t3 * 11.5676756F) +
          0.812945843F;
  K[11] =
      ((L0 * 2.00220537F - t2 * 6.61698914F) + t3 * 7.97767115F) + 0.757392108F;
}

/*
 * File trailer for lqr_k.c
 *
 * [EOF]
 */
