/*
 * File: lqr_k.c
 *
 * MATLAB Coder version            : 23.2
 * C/C++ source code generated on  : 12-Sep-2024 12:03:35
 */

/* Include Files */
#include "lqr_k.h"
#include "rt_nonfinite.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Declarations */
static float rt_powf_snf(float u0, float u1);

/* Function Definitions */
/*
 * Arguments    : float u0
 *                float u1
 * Return Type  : float
 */
static float rt_powf_snf(float u0, float u1)
{
  float y;
  if (rtIsNaNF(u0) || rtIsNaNF(u1)) {
    y = rtNaNF;
  } else {
    float f;
    float f1;
    f = fabsf(u0);
    f1 = fabsf(u1);
    if (rtIsInfF(u1)) {
      if (f == 1.0F) {
        y = 1.0F;
      } else if (f > 1.0F) {
        if (u1 > 0.0F) {
          y = rtInfF;
        } else {
          y = 0.0F;
        }
      } else if (u1 > 0.0F) {
        y = 0.0F;
      } else {
        y = rtInfF;
      }
    } else if (f1 == 0.0F) {
      y = 1.0F;
    } else if (f1 == 1.0F) {
      if (u1 > 0.0F) {
        y = u0;
      } else {
        y = 1.0F / u0;
      }
    } else if (u1 == 2.0F) {
      y = u0 * u0;
    } else if ((u1 == 0.5F) && (u0 >= 0.0F)) {
      y = sqrtf(u0);
    } else if ((u0 < 0.0F) && (u1 > floorf(u1))) {
      y = rtNaNF;
    } else {
      y = powf(u0, u1);
    }
  }
  return y;
}

/*
 * LQR_K
 *     K = LQR_K(L0)
 *
 * Arguments    : float L0
 *                float K[12]
 * Return Type  : void
 */
void lqr_k(float L0, float K[12])
{
  float t2;
  float t3;
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     2024-09-12 12:03:29 */
  t2 = L0 * L0;
  t3 = rt_powf_snf(L0, 3.0F);
  K[0] =
      ((L0 * -191.276474F + t2 * 188.654938F) - t3 * 73.5922852F) + 2.73185515F;
  K[1] =
      ((L0 * 304.748657F - t2 * 1278.07861F) + t3 * 1829.00403F) - 0.499778628F;
  K[2] = ((L0 * -12.4740305F - t2 * 55.6891441F) + t3 * 74.7139359F) +
         0.324489832F;
  K[3] =
      ((L0 * 38.5471191F - t2 * 116.782471F) + t3 * 143.253677F) - 0.330583066F;
  K[4] = ((L0 * -194.937897F + t2 * 652.828064F) - t3 * 830.448F) + 6.20440149F;
  K[5] =
      ((L0 * 88.3918228F - t2 * 801.901123F) + t3 * 1487.93726F) + 21.6825523F;
  K[6] =
      ((L0 * -127.829453F + t2 * 376.667419F) - t3 * 457.579742F) + 3.15122056F;
  K[7] = ((L0 * 76.2377F - t2 * 573.903381F) + t3 * 1019.18256F) + 13.6225023F;
  K[8] =
      ((L0 * -142.365631F - t2 * 101.852409F) + t3 * 601.560913F) + 63.0818748F;
  K[9] = ((L0 * 642.338F - t2 * 1845.69128F) + t3 * 1985.01477F) + 41.0441246F;
  K[10] =
      ((L0 * -7.60638762F - t2 * 34.0888748F) + t3 * 87.2749863F) + 6.65972805F;
  K[11] =
      ((L0 * 48.1233559F - t2 * 87.8985367F) + t3 * 31.8206635F) + 0.977147758F;
}

/*
 * File trailer for lqr_k.c
 *
 * [EOF]
 */
